"""Shared defaults for new Harness v3 training, collection, and evaluation runs."""

CONTEXT_WINDOW_TOKENS = 30000
GENERATION_RESERVE_TOKENS = 768
CONTEXT_SAFETY_MARGIN_TOKENS = 512
CONTEXT_INPUT_BUDGET_TOKENS = 28720
MAX_STEPS = 45

OBSERVATION_SEARCH_TOKEN_BUDGET = 2560
OBSERVATION_DETAIL_TOKEN_BUDGET = 3072
OBSERVATION_GENERIC_TOKEN_BUDGET = 512
OBSERVATION_CANDIDATE_MEMORY_TOKEN_BUDGET = 1024
OBSERVATION_SEARCH_TOP_K = 20

CANDIDATE_MEMORY_LIMIT = 4
CANDIDATE_RECOVERY_NO_PROGRESS_STEPS = 6
